version: '3.8'
services:
  web:
    image: visvirideveloper/petstore-front:latest
    ports:
    - "3000:80"
    restart: always

  db:
    image: visvirideveloper/petstore-db:latest
    ports:
    - "3306:3306"
    restart: always

  back:
    image: visvirideveloper/petstore-back:latest
    ports:
    - "3001:3001"
    restart: always
